name: prod-action
on:
  push:
    branches: [master]
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run-swap-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install

      - name: Generate daily volume, apy, tvl
        env:
          SWAP_STATS_FILE_PATH: swap-stats.json
          FLEEK_BUCKET: alphast0rm-team-bucket
          FLEEK_KEY_ID: ${{ secrets.FLEEK_KEY_ID }}
          FLEEK_KEY: ${{ secrets.FLEEK_KEY }}
          HTTP_PROVIDER_URL: ${{ secrets.HTTP_PROVIDER_URL }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}

        run: pipenv run python calc_apy_and_volume.py
  # run-pool-stats:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Set up Python
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: 3.8

  #     - name: Install pipenv
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install pipenv
  #         pipenv install

  #     - name: Generate stats and upload
  #       env:
  #         SWAP_CONTRACT_ADDRESS: "0x4f6A43Ad7cba042606dECaCA730d4CE0A57ac62e"
  #         DEPLOYMENT_BLOCK: 11685572
  #         HTTP_PROVIDER_URL: https://eth-mainnet.alchemyapi.io/v2/fSPdSsgYr5PfZg2du0EsuheqSN8rQQSY
  #         ADD_STATS_EVERY_N_BLOCK: 60
  #         STATS_FILE_PATH: pool-stats.json
  #         FLEEK_BUCKET: alphast0rm-team-bucket
  #         FLEEK_KEY_ID: ${{ secrets.FLEEK_KEY_ID }}
  #         FLEEK_KEY: ${{ secrets.FLEEK_KEY }}

  #       run: pipenv run python record_pool_stats.py
  # run-vol-stats:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Set up Python
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: 3.8

  #     - name: Install pipenv
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install pipenv
  #         pipenv install

  #     - name: Generate daily volume
  #       env:
  #         SWAP_CONTRACT_ADDRESS: "0x4f6A43Ad7cba042606dECaCA730d4CE0A57ac62e"
  #         HTTP_PROVIDER_URL: https://eth-mainnet.alchemyapi.io/v2/fSPdSsgYr5PfZg2du0EsuheqSN8rQQSY
  #         DAILY_VOL_FILE_PATH: daily-vol.json
  #         FLEEK_BUCKET: alphast0rm-team-bucket
  #         FLEEK_KEY_ID: ${{ secrets.FLEEK_KEY_ID }}
  #         FLEEK_KEY: ${{ secrets.FLEEK_KEY }}

  #       run: pipenv run python record_volume.py
